from mealoor.views.account import ShowAccountView
from mealoor.views.account import CreateAccountView
from mealoor.views.account import CreateTokenView
from mealoor.views.account import DeleteTokenView
from mealoor.views.account import ManageAccountView
from mealoor.views.account import WithdrawAccountView
from mealoor.views.body import ShowBodyView
from mealoor.views.body import CreateBodyView
from mealoor.views.body import UpdateBodyView
from mealoor.views.body import DeleteBodyView
from mealoor.views.eat import ListDateEatView
from mealoor.views.eat import CreateEatView
from mealoor.views.eat import UpdateEatView
from mealoor.views.eat import DeleteEatView
from mealoor.views.favoriteEat import ListFavoriteEatView
from mealoor.views.favoriteEat import CreateFavoriteEatView
from mealoor.views.favoriteEat import UpdateFavoriteEatView
from mealoor.views.favoriteEat import DeleteFavoriteEatView
from mealoor.views.favoriteEat import CreateEatFromFavoriteEatView
from mealoor.views.stock import ListStockView
from mealoor.views.stock import CreateStockView
from mealoor.views.stock import UpdateStockView
from mealoor.views.stock import DeleteStockView
from mealoor.views.stock import UseStockView
from mealoor.views.favoriteStock import ListFavoriteStockView
from mealoor.views.favoriteStock import CreateFavoriteStockView
from mealoor.views.favoriteStock import UpdateFavoriteStockView
from mealoor.views.favoriteStock import DeleteFavoriteStockView
from mealoor.views.favoriteStock import CreateStockFromFavoriteStockView
from mealoor.views.cook import CreateCookStockView
from mealoor.views.cook import CancelCookStockView
from mealoor.views.cookIngredient import ListCookIngredientView
from mealoor.views.use import ListUseView
from mealoor.views.use import DeleteUseView
