from mealoor.views.account import ShowAccountView
from mealoor.views.account import CreateAccountView
from mealoor.views.account import CreateTokenView
from mealoor.views.account import DeleteTokenView
from mealoor.views.account import ManageAccountView
from mealoor.views.account import WithdrawAccountView
from mealoor.views.body import ShowBodyView
from mealoor.views.body import CreateBodyView
from mealoor.views.body import UpdateBodyView
from mealoor.views.body import DeleteBodyView
from mealoor.views.eat import ListDateEatView
from mealoor.views.eat import CreateEatView
from mealoor.views.eat import UpdateEatView
from mealoor.views.eat import DeleteEatView
