export const foodCategory = [
  { value: "米" },
  { value: "パン" },
  { value: "麺" },
  { value: "いも" },
  { value: "大豆" },
  { value: "肉" },
  { value: "魚介" },
  { value: "卵" },
  { value: "淡色野菜" },
  { value: "緑黄色野菜" },
  { value: "きのこ" },
  { value: "フルーツ" },
  { value: "海藻" },
  { value: "乳製品" },
  { value: "飲み物" },
  { value: "お菓子" },
  { value: "お酒" },
  { value: "料理" },
];
